# This file was generated by the {rix} R package v0.17.2 on 2026-03-09
# with following call:
# >rix(date = "2026-03-02",
#  > r_pkgs = c("rvinecopulib",
#  > "ggplot2",
#  > "dplyr",
#  > "tidyr",
#  > "knitr",
#  > "kableExtra",
#  > "magick",
#  > "rmarkdown"),
#  > tex_pkgs = c("amsmath",
#  > "amsfonts",
#  > "amstex",
#  > "booktabs",
#  > "colortbl",
#  > "float",
#  > "makecell",
#  > "multirow",
#  > "natbib",
#  > "pdflscape",
#  > "tabu",
#  > "threeparttable",
#  > "threeparttablex",
#  > "ulem",
#  > "wrapfig",
#  > "microtype",
#  > "environ",
#  > "etoolbox",
#  > "footnotehyper",
#  > "bookmark",
#  > "trimspaces"),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-03-02.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      dplyr
      ggplot2
      kableExtra
      knitr
      magick
      rmarkdown
      rvinecopulib
      tidyr;
  };
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      amsfonts
      amsmath
      amstex
      bookmark
      booktabs
      colortbl
      environ
      etoolbox
      float
      footnotehyper
      makecell
      microtype
      multirow
      natbib
      pdflscape
      tabu
      threeparttable
      threeparttablex
      trimspaces
      ulem
      wrapfig;
  });
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R
      pandoc
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs tex system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
