library(rix)

rix(date = "2026-03-02",
    r_pkgs = c("rvinecopulib",
               "ggplot2",
               "dplyr",
               "tidyr",
               "knitr",
               "kableExtra",
               "magick",
               "rmarkdown"),
    tex_pkgs = c("amsmath",
                 "amsfonts",
                 "amstex",
                 "booktabs",
                 "colortbl",
                 "float",
                 "makecell",
                 "multirow",
                 "natbib",
                 "pdflscape",
                 "tabu",
                 "threeparttable",
                 "threeparttablex",
                 "ulem",
                 "wrapfig",
                 "microtype",
                 "environ",
                 "etoolbox",
                 "footnotehyper",
                 "bookmark",
                 "trimspaces"),
    ide = "none",
    project_path = ".",
    overwrite = TRUE)
